In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)

In [4]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [6]:
print(f"x.shape: {X_train.shape}, type: {type(X_train)}")
print(X_train)
print(f"y.shape: {y_train.shape}, type: {type(y_train)}")
print(y_train)

x.shape: (3, 4), type: <class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y.shape: (3,), type: <class 'numpy.ndarray'>
[460 232 178]


In [7]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [8]:
def predict_single_loop(x, w, b):
    """Single predict using linear regression"""
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p + p_i
    p = p + b
    return p

In [9]:
x_vec = X_train[0, :]
print(f"x_vec shape: {x_vec.shape}, value: {x_vec}")

# predict
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f"f_wb shape: {f_wb.shape}, prediction: {f_wb}")

x_vec shape: (4,), value: [2104    5    1   45]
f_wb shape: (), prediction: 459.9999976194083


In [10]:
def predict(x, w, b):
    """single predict using LS"""
    p = np.dot(x, w) + b
    return p

In [ ]:
x_vec = X_train[0, :]
f_wb = predict(x_vec, w_init, b_init)
print('predicted: ', f_wb)

predicted:  459.9999976194083
